// PLAN-temak 2B: a témák betűi. Statikus TTF/OTF (a variable font Androidon nem jó),
// a kulcs a `useFonts` neve, vagyis a `fontFamily` értéke. A forrás a Google Fonts
// (@expo-google-fonts statikus példányai), az OpenDyslexic a saját repójából.
// ShipporiMincho (8,6 MB) helyett Spectral-Light (a PLAN-temak.md 2B/2. pontja szerint).

export const FONT_NAMES = [
  'PoiretOne',
  'JosefinSans',
  'AlfaSlabOne',
  'Atkinson',
  'Atkinson-Bold',
  'Lexend',
  'VT323',
  'Syne-ExtraBold',
  'Fredoka-Medium',
  'Orbitron-Bold',
  'Cormorant-MediumItalic',
  'Spectral-Light',
  'Playfair-Black',
  'Oswald-Bold',
  'RussoOne',
  'Pacifico',
  'Jost',
  'Jost-Bold',
  'Bangers',
  'CinzelDecorative-Bold',
  'Marcellus',
  'YesevaOne',
  'RubikMonoOne',
  'UnifrakturMaguntia',
  'IMFellEnglish',
  'RubikSprayPaint',
  'PermanentMarker',
  'OpenDyslexic',
] as const;

type FontName = (typeof FONT_NAMES)[number];

export const FONT_FILES: Record<FontName, number> = {
  PoiretOne: require('../assets/fonts/PoiretOne-Regular.ttf'),
  JosefinSans: require('../assets/fonts/JosefinSans-Regular.ttf'),
  AlfaSlabOne: require('../assets/fonts/AlfaSlabOne-Regular.ttf'),
  Atkinson: require('../assets/fonts/AtkinsonHyperlegible-Regular.ttf'),
  'Atkinson-Bold': require('../assets/fonts/AtkinsonHyperlegible-Bold.ttf'),
  Lexend: require('../assets/fonts/Lexend-Regular.ttf'),
  VT323: require('../assets/fonts/VT323-Regular.ttf'),
  'Syne-ExtraBold': require('../assets/fonts/Syne-ExtraBold.ttf'),
  'Fredoka-Medium': require('../assets/fonts/Fredoka-Medium.ttf'),
  'Orbitron-Bold': require('../assets/fonts/Orbitron-Bold.ttf'),
  'Cormorant-MediumItalic': require('../assets/fonts/Cormorant-MediumItalic.ttf'),
  'Spectral-Light': require('../assets/fonts/Spectral-Light.ttf'),
  'Playfair-Black': require('../assets/fonts/PlayfairDisplay-Black.ttf'),
  'Oswald-Bold': require('../assets/fonts/Oswald-Bold.ttf'),
  RussoOne: require('../assets/fonts/RussoOne-Regular.ttf'),
  Pacifico: require('../assets/fonts/Pacifico-Regular.ttf'),
  Jost: require('../assets/fonts/Jost-Regular.ttf'),
  'Jost-Bold': require('../assets/fonts/Jost-Bold.ttf'),
  Bangers: require('../assets/fonts/Bangers-Regular.ttf'),
  'CinzelDecorative-Bold': require('../assets/fonts/CinzelDecorative-Bold.ttf'),
  Marcellus: require('../assets/fonts/Marcellus-Regular.ttf'),
  YesevaOne: require('../assets/fonts/YesevaOne-Regular.ttf'),
  RubikMonoOne: require('../assets/fonts/RubikMonoOne-Regular.ttf'),
  UnifrakturMaguntia: require('../assets/fonts/UnifrakturMaguntia-Regular.ttf'),
  IMFellEnglish: require('../assets/fonts/IMFellEnglish-Regular.ttf'),
  RubikSprayPaint: require('../assets/fonts/RubikSprayPaint-Regular.ttf'),
  PermanentMarker: require('../assets/fonts/PermanentMarker-Regular.ttf'),
  OpenDyslexic: require('../assets/fonts/OpenDyslexic-Regular.otf'),
};

type FontLicense = { family: string; license: string; url: string };

const OFL = 'SIL Open Font License 1.1';
const gf = (family: string, license: string = OFL): FontLicense => ({
  family,
  license,
  url: `https://fonts.google.com/specimen/${family.replace(/ /g, '+')}`,
});

export const FONT_LICENSES: Record<FontName, FontLicense> = {
  PoiretOne: gf('Poiret One'),
  JosefinSans: gf('Josefin Sans'),
  AlfaSlabOne: gf('Alfa Slab One'),
  Atkinson: gf('Atkinson Hyperlegible'),
  'Atkinson-Bold': gf('Atkinson Hyperlegible'),
  Lexend: gf('Lexend'),
  VT323: gf('VT323'),
  'Syne-ExtraBold': gf('Syne'),
  'Fredoka-Medium': gf('Fredoka'),
  'Orbitron-Bold': gf('Orbitron'),
  'Cormorant-MediumItalic': gf('Cormorant'),
  'Spectral-Light': gf('Spectral'),
  'Playfair-Black': gf('Playfair Display'),
  'Oswald-Bold': gf('Oswald'),
  RussoOne: gf('Russo One'),
  Pacifico: gf('Pacifico'),
  Jost: gf('Jost'),
  'Jost-Bold': gf('Jost'),
  Bangers: gf('Bangers'),
  'CinzelDecorative-Bold': gf('Cinzel Decorative'),
  Marcellus: gf('Marcellus'),
  YesevaOne: gf('Yeseva One'),
  RubikMonoOne: gf('Rubik Mono One'),
  UnifrakturMaguntia: gf('UnifrakturMaguntia'),
  IMFellEnglish: gf('IM Fell English'),
  RubikSprayPaint: gf('Rubik Spray Paint'),
  PermanentMarker: gf('Permanent Marker', 'Apache License 2.0'),
  OpenDyslexic: {
    family: 'OpenDyslexic',
    license: OFL,
    url: 'https://github.com/antijingoist/opendyslexic',
  },
};
