// Expo config plugin: ship native debug symbols with the Play bundle.
//
// expo-build-properties has no option for it, and android/ is regenerated by `expo prebuild`,
// so the release build type of the generated app/build.gradle is patched here. Play Console
// uses the symbol table to symbolicate native crashes; APK builds are not affected.
const { withAppBuildGradle } = require('expo/config-plugins');

const SNIPPET = "            ndk {\n                debugSymbolLevel 'SYMBOL_TABLE'\n            }\n";

function patchBuildGradle(src) {
  if (src.includes('debugSymbolLevel')) return src;
  const out = src.replace(/^( {8}release \{\n)/m, `$1${SNIPPET}`);
  if (out === src) throw new Error('withNativeDebugSymbols: buildTypes.release anchor not found');
  return out;
}

const withNativeDebugSymbols = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withNativeDebugSymbols: expected a Groovy android/app/build.gradle');
    }
    cfg.modResults.contents = patchBuildGradle(cfg.modResults.contents);
    return cfg;
  });

module.exports = withNativeDebugSymbols;
module.exports.patchBuildGradle = patchBuildGradle;
