const fs = require('fs');
const path = require('path');

const germanData = {
  // A0
  1: { de: 'nein', sentence_de: 'Ich will nicht gehen.' },
  2: { de: 'ja', sentence_de: 'Ja, natürlich.' },
  3: { de: 'ich', sentence_de: 'Ich bin von hier.' },
  4: { de: 'was', sentence_de: 'Was passiert?' },
  5: { de: 'ist', sentence_de: 'Es ist sehr gut.' },
  6: { de: 'gut', sentence_de: 'Mir geht es gut.' },
  7: { de: 'aber', sentence_de: 'Aber ich kann nicht.' },
  8: { de: 'hier', sentence_de: 'Komm hier.' },
  9: { de: 'sehr', sentence_de: 'Es ist sehr groß.' },
  10: { de: 'alles', sentence_de: 'Alles ist in Ordnung.' },
  11: { de: 'nichts', sentence_de: 'Kein Problem.' },
  12: { de: 'jetzt', sentence_de: 'Lass uns jetzt gehen.' },
  13: { de: 'Zeit', sentence_de: 'Ich habe keine Zeit.' },
  14: { de: 'Haus / Zuhause', sentence_de: 'Ich gehe nach Hause.' },
  15: { de: 'Leben', sentence_de: 'So ist das Leben.' },
  16: { de: 'Mann', sentence_de: 'Er ist ein guter Mann.' },
  17: { de: 'Frau', sentence_de: 'Diese Frau ist stark.' },
  18: { de: 'gut', sentence_de: 'Gut, lass uns gehen.' },
  19: { de: 'schlecht', sentence_de: 'Es ist nicht schlecht.' },
  20: { de: 'groß', sentence_de: 'Es ist eine große Stadt.' },
  21: { de: 'Geld', sentence_de: 'Ich habe kein Geld.' },
  22: { de: 'Freund', sentence_de: 'Er ist mein bester Freund.' },
  23: { de: 'Liebe', sentence_de: 'Liebe ist alles.' },
  24: { de: 'Wasser', sentence_de: 'Ich möchte Wasser.' },
  25: { de: 'essen', sentence_de: 'Lass uns essen gehen.' },
  26: { de: 'schlafen', sentence_de: 'Ich will schlafen.' },
  27: { de: 'sprechen', sentence_de: 'Ich muss mit dir sprechen.' },
  28: { de: 'wissen', sentence_de: 'Ich weiß es nicht.' },
  29: { de: 'können', sentence_de: 'Kann ich gehen?' },
  30: { de: 'wollen / lieben', sentence_de: 'Ich liebe dich sehr.' },
  31: { de: 'gehen', sentence_de: 'Ich gehe morgen.' },
  32: { de: 'kommen', sentence_de: 'Komm mit mir.' },
  33: { de: 'haben', sentence_de: 'Ich habe Hunger.' },
  34: { de: 'machen / tun', sentence_de: 'Was wirst du machen?' },
  35: { de: 'sagen', sentence_de: 'Was willst du sagen?' },
  36: { de: 'geben', sentence_de: 'Gib mir einen Moment.' },
  37: { de: 'sehen', sentence_de: 'Ich will das sehen.' },
  38: { de: 'glauben', sentence_de: 'Ich kann es nicht glauben.' },
  39: { de: 'finden', sentence_de: 'Ich kann es nicht finden.' },
  40: { de: 'anrufen', sentence_de: 'Ich werde dich anrufen.' },
  41: { de: 'Name', sentence_de: 'Wie heißt du?' },
  42: { de: 'Mutter', sentence_de: 'Meine Mutter ist wunderbar.' },
  43: { de: 'Vater', sentence_de: 'Mein Vater arbeitet viel.' },
  44: { de: 'Sohn', sentence_de: 'Er ist mein Sohn.' },
  45: { de: 'neu', sentence_de: 'Ich habe einen neuen Job.' },
  46: { de: 'klein', sentence_de: 'Es ist sehr klein.' },
  47: { de: 'gleich / dasselbe', sentence_de: 'Es ist dasselbe.' },
  48: { de: 'Welt', sentence_de: 'Er ist der Beste der Welt.' },
  49: { de: 'Tag', sentence_de: 'Heute ist ein guter Tag.' },
  50: { de: 'Nacht', sentence_de: 'Gute Nacht.' },
  51: { de: 'danke', sentence_de: 'Vielen Dank.' },
  52: { de: 'bitte', sentence_de: 'Hilf mir, bitte.' },
  53: { de: 'Entschuldigung', sentence_de: 'Entschuldigung, ich wusste es nicht.' },
  54: { de: 'hallo', sentence_de: 'Hallo! Wie geht es dir?' },
  55: { de: 'Tschüss', sentence_de: 'Tschüss, Freund.' },
  56: { de: 'morgen / Morgen', sentence_de: 'Wir sehen uns morgen.' },
  57: { de: 'immer', sentence_de: 'Ich werde dich immer lieben.' },
  58: { de: 'nie', sentence_de: 'Sag niemals nie.' },
  59: { de: 'auch', sentence_de: 'Ich auch.' },
  60: { de: 'noch', sentence_de: 'Noch nicht.' },
  61: { de: 'zwischen', sentence_de: 'Zwischen dir und mir.' },
  62: { de: 'danach / später', sentence_de: 'Wir reden später.' },
  63: { de: 'vorher', sentence_de: 'Wie vorher.' },
  64: { de: 'draußen', sentence_de: 'Lass uns rausgehen.' },
  65: { de: 'drinnen', sentence_de: 'Es ist drinnen.' },
  66: { de: 'Herz', sentence_de: 'Mit meinem ganzen Herzen.' },
  67: { de: 'Kopf', sentence_de: 'Mein Kopf tut weh.' },
  68: { de: 'Hand', sentence_de: 'Gib mir deine Hand.' },
  69: { de: 'Augen', sentence_de: 'Du hast schöne Augen.' },
  70: { de: 'Essen', sentence_de: 'Das Essen ist fertig.' },
  71: { de: 'glücklich', sentence_de: 'Ich bin glücklich.' },
  72: { de: 'traurig', sentence_de: 'Ich bin traurig.' },
  73: { de: 'Angst', sentence_de: 'Ich habe Angst.' },
  74: { de: 'Wahrheit / wahr', sentence_de: 'Ist das wahr?' },
  75: { de: 'Lüge', sentence_de: 'Das ist eine Lüge.' },
  76: { de: 'Problem', sentence_de: 'Kein Problem.' },
  77: { de: 'Hilfe', sentence_de: 'Ich brauche Hilfe.' },
  78: { de: 'denken', sentence_de: 'Was denkst du?' },
  79: { de: 'fühlen', sentence_de: 'Wie fühlst du dich?' },
  80: { de: 'warten / hoffen', sentence_de: 'Warte einen Moment.' },
  81: { de: 'verstehen', sentence_de: 'Ich verstehe nicht.' },
  82: { de: 'leben', sentence_de: 'Wo lebst du?' },
  83: { de: 'sterben', sentence_de: 'Ich will nicht sterben.' },
  84: { de: 'mögen / gefallen', sentence_de: 'Es gefällt mir sehr.' },
  85: { de: 'brauchen', sentence_de: 'Ich brauche dich.' },
  86: { de: 'zusammen', sentence_de: 'Lass uns zusammen gehen.' },
  87: { de: 'allein / nur', sentence_de: 'Ich bin allein.' },
  88: { de: 'verrückt', sentence_de: 'Du bist verrückt!' },
  89: { de: 'sicher', sentence_de: 'Bist du sicher?' },
  90: { de: 'schnell', sentence_de: 'Komm schnell.' },
  91: { de: 'langsam', sentence_de: 'Sprich langsamer.' },
  92: { de: 'schön / hübsch', sentence_de: 'Wie schön.' },
  93: { de: 'stark', sentence_de: 'Du bist sehr stark.' },
  94: { de: 'schwierig', sentence_de: 'Es ist sehr schwierig.' },
  95: { de: 'einfach / leicht', sentence_de: 'Es ist einfach.' },
  96: { de: 'wichtig', sentence_de: 'Es ist sehr wichtig.' },
  97: { de: 'Sache / Ding', sentence_de: 'Das ist eine seltsame Sache.' },
  98: { de: 'Ort / Platz', sentence_de: 'Das ist ein guter Ort.' },
  99: { de: 'Leute / Menschen', sentence_de: 'Es gibt viele Leute.' },
  100: { de: 'Stunde / Uhrzeit', sentence_de: 'Wie spät ist es?' },
  // A1
  101: { de: 'Straße', sentence_de: 'Ich wohne in dieser Straße.' },
  102: { de: 'Laden / Geschäft', sentence_de: 'Der Laden ist geschlossen.' },
  103: { de: 'Tisch', sentence_de: 'Das Essen ist auf dem Tisch.' },
  104: { de: 'Stuhl', sentence_de: 'Setz dich auf den Stuhl.' },
  105: { de: 'Buch', sentence_de: 'Ich mag dieses Buch.' },
  106: { de: 'Hund', sentence_de: 'Ich habe einen Hund.' },
  107: { de: 'Katze', sentence_de: 'Die Katze schläft.' },
  108: { de: 'rot', sentence_de: 'Ich mag Rot.' },
  109: { de: 'blau', sentence_de: 'Der Himmel ist blau.' },
  110: { de: 'grün', sentence_de: 'Das Gras ist grün.' },
  111: { de: 'eins', sentence_de: 'Ich habe nur eins.' },
  112: { de: 'zwei', sentence_de: 'Wir sind zu zweit.' },
  113: { de: 'drei', sentence_de: 'Ich habe drei Geschwister.' },
  114: { de: 'Geschwister / Bruder', sentence_de: 'Mein Bruder ist älter.' },
  115: { de: 'Schule', sentence_de: 'Ich gehe in die Schule.' },
  116: { de: 'lesen', sentence_de: 'Ich lese gern.' },
  117: { de: 'schreiben', sentence_de: 'Ich muss einen Brief schreiben.' },
  118: { de: 'kaufen', sentence_de: 'Ich kaufe Brot.' },
  119: { de: 'Brot', sentence_de: 'Das Brot ist frisch.' },
  120: { de: 'Milch', sentence_de: 'Ich möchte Milch.' },
  121: { de: 'Kaffee', sentence_de: 'Einen Kaffee, bitte.' },
  122: { de: 'kalt', sentence_de: 'Heute ist es kalt.' },
  123: { de: 'heiß / warm', sentence_de: 'Der Kaffee ist heiß.' },
  124: { de: 'Regen', sentence_de: 'Ich mag keinen Regen.' },
  125: { de: 'Sonne', sentence_de: 'Heute scheint die Sonne.' },
  126: { de: 'spazieren', sentence_de: 'Lass uns spazieren gehen.' },
  127: { de: 'laufen / rennen', sentence_de: 'Ich laufe gern.' },
  128: { de: 'spielen', sentence_de: 'Die Kinder spielen.' },
  129: { de: 'Kind', sentence_de: 'Er ist ein glückliches Kind.' },
  130: { de: 'Stadt', sentence_de: 'Diese Stadt ist schön.' },
  131: { de: 'Land', sentence_de: 'Mein Land ist groß.' },
  132: { de: 'Küche', sentence_de: 'Ich bin in der Küche.' },
  133: { de: 'Badezimmer', sentence_de: 'Wo ist das Badezimmer?' },
  134: { de: 'Bett', sentence_de: 'Ich will ins Bett.' },
  135: { de: 'Fenster', sentence_de: 'Öffne das Fenster.' },
  136: { de: 'Tür', sentence_de: 'Schließ die Tür.' },
  137: { de: 'Arbeit', sentence_de: 'Ich habe viel Arbeit.' },
  138: { de: 'Auto', sentence_de: 'Ich fahre mit dem Auto.' },
  139: { de: 'Bus', sentence_de: 'Der Bus kommt spät.' },
  140: { de: 'links', sentence_de: 'Biege links ab.' },
  141: { de: 'rechts', sentence_de: 'Es ist rechts.' },
  142: { de: 'nah', sentence_de: 'Es ist sehr nah.' },
  143: { de: 'weit', sentence_de: 'Es ist weit von hier.' },
  144: { de: 'oben', sentence_de: 'Schau nach oben.' },
  145: { de: 'unten', sentence_de: 'Es ist unten.' },
  146: { de: 'Krankenhaus', sentence_de: 'Wo ist das Krankenhaus?' },
  147: { de: 'Arzt', sentence_de: 'Ich brauche einen Arzt.' },
  148: { de: 'krank', sentence_de: 'Ich bin krank.' },
  149: { de: 'zufrieden', sentence_de: 'Ich bin zufrieden.' },
  150: { de: 'müde', sentence_de: 'Ich bin sehr müde.' },
  // A2
  201: { de: 'Erinnerung', sentence_de: 'Ich habe eine gute Erinnerung.' },
  202: { de: 'Reise', sentence_de: 'Es war eine gute Reise.' },
  203: { de: 'Flughafen', sentence_de: 'Wir fahren zum Flughafen.' },
  204: { de: 'Koffer', sentence_de: 'Mein Koffer ist schwer.' },
  205: { de: 'Reservierung', sentence_de: 'Ich habe eine Reservierung.' },
  206: { de: 'Rechnung', sentence_de: 'Die Rechnung, bitte.' },
  207: { de: 'Trinkgeld', sentence_de: 'Ich habe ein Trinkgeld gelassen.' },
  208: { de: 'Preis', sentence_de: 'Was ist der Preis?' },
  209: { de: 'billig / günstig', sentence_de: 'Es ist sehr günstig.' },
  210: { de: 'teuer', sentence_de: 'Es ist zu teuer.' },
  211: { de: 'Nachbar', sentence_de: 'Mein Nachbar ist nett.' },
  212: { de: 'Film', sentence_de: 'Lass uns einen Film sehen.' },
  213: { de: 'Lied', sentence_de: 'Ich mag dieses Lied.' },
  214: { de: 'kochen', sentence_de: 'Ich koche gern.' },
  215: { de: 'putzen / reinigen', sentence_de: 'Ich muss das Haus putzen.' },
  216: { de: 'einladen', sentence_de: 'Ich lade dich zum Abendessen ein.' },
  217: { de: 'Geschenk', sentence_de: 'Das ist ein Geschenk für dich.' },
  218: { de: 'Party / Feier', sentence_de: 'Lass uns zur Party gehen.' },
  219: { de: 'Geburtstag', sentence_de: 'Alles Gute zum Geburtstag!' },
  220: { de: 'Urlaub', sentence_de: 'Ich brauche Urlaub.' },
  221: { de: 'Strand', sentence_de: 'Lass uns zum Strand gehen.' },
  222: { de: 'Berg', sentence_de: 'Der Berg ist hoch.' },
  223: { de: 'Fluss', sentence_de: 'Der Fluss ist lang.' },
  224: { de: 'Wald', sentence_de: 'Ich mag den Wald.' },
  225: { de: 'Blume', sentence_de: 'Was für eine schöne Blume.' },
  226: { de: 'Stern', sentence_de: 'Schau dir die Sterne an.' },
  227: { de: 'Mond', sentence_de: 'Der Mond ist heute groß.' },
  228: { de: 'Wolke', sentence_de: 'Es gibt viele Wolken.' },
  229: { de: 'Wind', sentence_de: 'Es ist sehr windig.' },
  230: { de: 'Frühling', sentence_de: 'Ich mag den Frühling.' },
  231: { de: 'Sommer', sentence_de: 'Im Sommer ist es heiß.' },
  232: { de: 'Herbst', sentence_de: 'Der Herbst ist schön.' },
  233: { de: 'Winter', sentence_de: 'Ich mag den Winter nicht.' },
  234: { de: 'erklären', sentence_de: 'Kannst du es erklären?' },
  235: { de: 'fragen', sentence_de: 'Kann ich etwas fragen?' },
  236: { de: 'antworten', sentence_de: 'Ich kann nicht antworten.' },
  237: { de: 'vergessen', sentence_de: 'Ich will nicht vergessen.' },
  238: { de: 'sich erinnern', sentence_de: 'Ich kann mich nicht erinnern.' },
  239: { de: 'helfen', sentence_de: 'Kannst du mir helfen?' },
  240: { de: 'ändern / wechseln', sentence_de: 'Ich will das Thema wechseln.' },
  241: { de: 'bezahlen', sentence_de: 'Ich will mit Karte bezahlen.' },
  242: { de: 'versuchen / probieren', sentence_de: 'Ich will das probieren.' },
  243: { de: 'gefährlich', sentence_de: 'Es ist gefährlich.' },
  244: { de: 'ruhig', sentence_de: 'Dieser Ort ist ruhig.' },
  245: { de: 'beschäftigt', sentence_de: 'Ich bin sehr beschäftigt.' },
  246: { de: 'frei', sentence_de: 'Bist du morgen frei?' },
  247: { de: 'offen / geöffnet', sentence_de: 'Der Laden ist geöffnet.' },
  248: { de: 'geschlossen', sentence_de: 'Sonntags ist geschlossen.' },
  249: { de: 'voll', sentence_de: 'Das Restaurant ist voll.' },
  250: { de: 'leer', sentence_de: 'Die Flasche ist leer.' },
  // B1
  301: { de: 'Entwicklung', sentence_de: 'Die Entwicklung ist langsam.' },
  302: { de: 'Gesellschaft', sentence_de: 'Die Gesellschaft verändert sich.' },
  303: { de: 'Regierung', sentence_de: 'Die Regierung hat entschieden.' },
  304: { de: 'Firma / Unternehmen', sentence_de: 'Ich arbeite in einer Firma.' },
  305: { de: 'Beschäftigung / Stelle', sentence_de: 'Ich suche eine Stelle.' },
  306: { de: 'Gehalt', sentence_de: 'Das Gehalt ist niedrig.' },
  307: { de: 'Erfahrung', sentence_de: 'Ich habe Erfahrung.' },
  308: { de: 'Umwelt', sentence_de: 'Die Umwelt ist gut.' },
  309: { de: 'Meinung', sentence_de: 'Was ist deine Meinung?' },
  310: { de: 'Vereinbarung', sentence_de: 'Ich bin einverstanden.' },
  311: { de: 'lösen', sentence_de: 'Wir müssen das lösen.' },
  312: { de: 'erreichen / bekommen', sentence_de: 'Ich werde es bekommen.' },
  313: { de: 'aufrechterhalten', sentence_de: 'Man muss die Ruhe bewahren.' },
  314: { de: 'anbieten', sentence_de: 'Kann ich dir etwas anbieten?' },
  315: { de: 'vorschlagen', sentence_de: 'Ich möchte etwas vorschlagen.' },
  316: { de: 'diskutieren / streiten', sentence_de: 'Ich will nicht streiten.' },
  317: { de: 'bauen', sentence_de: 'Sie werden eine Brücke bauen.' },
  318: { de: 'zerstören', sentence_de: 'Ich will nichts zerstören.' },
  319: { de: 'schützen', sentence_de: 'Man muss die Natur schützen.' },
  320: { de: 'entdecken', sentence_de: 'Ich will die Welt entdecken.' },
  321: { de: 'untersuchen / erforschen', sentence_de: 'Wir müssen mehr erforschen.' },
  322: { de: 'Ergebnis', sentence_de: 'Das Ergebnis ist gut.' },
  323: { de: 'Erfolg', sentence_de: 'Es war ein großer Erfolg.' },
  324: { de: 'Misserfolg / Scheitern', sentence_de: 'Es war kein Misserfolg.' },
  325: { de: 'Anstrengung', sentence_de: 'Die Anstrengung lohnt sich.' },
  326: { de: 'Ziel', sentence_de: 'Mein Ziel ist klar.' },
  327: { de: 'Vorschlag', sentence_de: 'Ich habe einen Vorschlag.' },
  328: { de: 'Lösung', sentence_de: 'Es gibt eine Lösung.' },
  329: { de: 'Vorteil', sentence_de: 'Es ist ein großer Vorteil.' },
  330: { de: 'Nachteil', sentence_de: 'Es gibt auch Nachteile.' },
  331: { de: 'abhängen', sentence_de: 'Es hängt von dir ab.' },
  332: { de: 'beeinflussen', sentence_de: 'Es kann viel beeinflussen.' },
  333: { de: 'verbessern', sentence_de: 'Ich will mein Spanisch verbessern.' },
  334: { de: 'reduzieren / verringern', sentence_de: 'Man muss die Kosten reduzieren.' },
  335: { de: 'erhöhen / steigern', sentence_de: 'Die Preise werden steigen.' },
  336: { de: 'vergleichen', sentence_de: 'Du kannst nicht vergleichen.' },
  337: { de: 'wählen / auswählen', sentence_de: 'Du musst wählen.' },
  338: { de: 'erlauben', sentence_de: 'Es ist nicht erlaubt.' },
  339: { de: 'verbieten', sentence_de: 'Rauchen ist verboten.' },
  340: { de: 'zwingen', sentence_de: 'Niemand zwingt dich.' },
  341: { de: 'verantwortlich', sentence_de: 'Du bist verantwortlich.' },
  342: { de: 'schuldig', sentence_de: 'Ich bin nicht schuldig.' },
  343: { de: 'stolz', sentence_de: 'Ich bin stolz auf dich.' },
  344: { de: 'mutig / tapfer', sentence_de: 'Du bist sehr mutig.' },
  345: { de: 'ehrlich', sentence_de: 'Sei ehrlich mit mir.' },
  346: { de: 'gerecht / fair', sentence_de: 'Es ist nicht fair.' },
  347: { de: 'fähig', sentence_de: 'Du bist zu allem fähig.' },
  348: { de: 'verfügbar', sentence_de: 'Es ist nicht verfügbar.' },
  349: { de: 'nötig / notwendig', sentence_de: 'Es ist notwendig.' },
  350: { de: 'genug / ausreichend', sentence_de: 'Das reicht schon.' },
  // B2
  401: { de: 'unentbehrlich', sentence_de: 'Es ist unentbehrlich, pünktlich zu sein.' },
  402: { de: 'tendieren / neigen', sentence_de: 'Ich neige dazu, Dinge zu vergessen.' },
  403: { de: 'erschwinglich', sentence_de: 'Der Preis ist erschwinglich.' },
  404: { de: 'Nuance', sentence_de: 'Es gibt eine wichtige Nuance.' },
  405: { de: 'Frist', sentence_de: 'Die Frist ist morgen.' },
  406: { de: 'Investition', sentence_de: 'Es war eine gute Investition.' },
  407: { de: 'Budget / Haushalt', sentence_de: 'Das Budget ist begrenzt.' },
  408: { de: 'rentabel / profitabel', sentence_de: 'Das Geschäft ist rentabel.' },
  409: { de: 'erreichen', sentence_de: 'Wir werden das Ziel erreichen.' },
  410: { de: 'überwinden / übertreffen', sentence_de: 'Du kannst das überwinden.' },
  411: { de: 'beitragen', sentence_de: 'Ich möchte etwas beitragen.' },
  412: { de: 'aufwerfen / vorschlagen', sentence_de: 'Ich möchte eine Idee aufwerfen.' },
  413: { de: 'angehen / behandeln', sentence_de: 'Wir müssen das Problem angehen.' },
  414: { de: 'fördern', sentence_de: 'Wir müssen die Bildung fördern.' },
  415: { de: 'ausüben / erfüllen', sentence_de: 'Er spielt eine wichtige Rolle.' },
  416: { de: 'verknüpfen / verbinden', sentence_de: 'Sie sind miteinander verbunden.' },
  417: { de: 'entstehen / auftauchen', sentence_de: 'Ein Problem ist aufgetaucht.' },
  418: { de: 'hervorstechen', sentence_de: 'Sie sticht in ihrer Arbeit hervor.' },
  419: { de: 'übernehmen', sentence_de: 'Ich übernehme die Verantwortung.' },
  420: { de: 'Herausforderung', sentence_de: 'Es ist eine große Herausforderung.' },
  421: { de: 'Bereich', sentence_de: 'Im beruflichen Bereich.' },
  422: { de: 'Leistung', sentence_de: 'Die Leistung ist gut.' },
  423: { de: 'Verwaltung / Management', sentence_de: 'Die Verwaltung ist effizient.' },
  424: { de: 'Verpflichtung / Engagement', sentence_de: 'Ich habe eine Verpflichtung.' },
  425: { de: 'Kriterium', sentence_de: 'Was ist das Kriterium?' },
  426: { de: 'gültig / geltend', sentence_de: 'Das Gesetz ist geltend.' },
  427: { de: 'allmählich', sentence_de: 'Die Veränderung ist allmählich.' },
  428: { de: 'alltäglich', sentence_de: 'Es gehört zum Alltag.' },
  429: { de: 'unerwartet', sentence_de: 'Etwas Unerwartetes ist passiert.' },
  430: { de: 'Wegwerf- / Einweg-', sentence_de: 'Es ist ein Einwegprodukt.' },
  431: { de: 'nutzen / ausnutzen', sentence_de: 'Man muss die Gelegenheit nutzen.' },
  432: { de: 'bereitstellen / liefern', sentence_de: 'Wir werden die Information bereitstellen.' },
  433: { de: 'einbeziehen', sentence_de: 'Alle müssen einbezogen werden.' },
  434: { de: 'verlegen / transferieren', sentence_de: 'Sie verlegen das Büro.' },
  435: { de: 'unterstützen', sentence_de: 'Ich werde dich unterstützen.' },
  436: { de: 'unternehmen / gründen', sentence_de: 'Ich will ein Geschäft gründen.' },
  437: { de: 'aufrechterhalten / halten', sentence_de: 'Man muss die Anstrengung aufrechterhalten.' },
  438: { de: 'erneuern', sentence_de: 'Ich muss den Vertrag erneuern.' },
  439: { de: 'einschränken', sentence_de: 'Sie werden den Zugang einschränken.' },
  440: { de: 'wahrnehmen', sentence_de: 'Ich kann den Unterschied nicht wahrnehmen.' },
  441: { de: 'vorbeugen / verhindern', sentence_de: 'Man muss das Problem verhindern.' },
  442: { de: 'überzeugen', sentence_de: 'Kann ich dich nicht überzeugen?' },
  443: { de: 'fordern / verlangen', sentence_de: 'Ich werde eine Erklärung fordern.' },
  444: { de: 'erkennen / anerkennen', sentence_de: 'Man muss den Fehler anerkennen.' },
  445: { de: 'verachten', sentence_de: 'Du sollst niemanden verachten.' },
  446: { de: 'dankbar sein', sentence_de: 'Ich bin dir sehr dankbar.' },
  447: { de: 'bereuen', sentence_de: 'Ich bereue es nicht.' },
  448: { de: 'sich trauen / wagen', sentence_de: 'Ich traue mich nicht.' },
  449: { de: 'Neid', sentence_de: 'Neid ist schlecht.' },
  450: { de: 'Hochmut / Überheblichkeit', sentence_de: 'Hochmut ist ein Fehler.' },
  // C1
  501: { de: 'Knappheit / Mangel', sentence_de: 'Es herrscht Wassermangel.' },
  502: { de: 'Aufschwung / Boom', sentence_de: 'Die Industrie boomt.' },
  503: { de: 'Art / Natur', sentence_de: 'Es ist persönlicher Natur.' },
  504: { de: 'Tragweite / Ausmaß', sentence_de: 'Ein Projekt von großer Tragweite.' },
  505: { de: 'umfassen', sentence_de: 'Der Plan umfasst alles.' },
  506: { de: 'hervorrufen / auslösen', sentence_de: 'Die Nachricht löste Kontroversen aus.' },
  507: { de: 'verzichten / absehen von', sentence_de: 'Ich kann nicht auf dich verzichten.' },
  508: { de: 'abtrennen / loslösen', sentence_de: 'Man muss die Themen trennen.' },
  509: { de: 'beheben / korrigieren', sentence_de: 'Der Fehler muss behoben werden.' },
  510: { de: 'mit sich bringen', sentence_de: 'Es bringt gewisse Risiken mit sich.' },
  511: { de: 'befolgen / einhalten', sentence_de: 'Man muss die Regeln befolgen.' },
  512: { de: 'ablehnen / abweisen', sentence_de: 'Sie lehnten den Vorschlag ab.' },
  513: { de: 'schmälern / beeinträchtigen', sentence_de: 'Ich will deine Arbeit nicht schmälern.' },
  514: { de: 'anstürmen / angreifen', sentence_de: 'Der Stier griff an.' },
  515: { de: 'vorbringen (Argument)', sentence_de: 'Er brachte ein gutes Argument vor.' },
  516: { de: 'Schaden / Nachteil', sentence_de: 'Unbeschadet des Vorstehenden.' },
  517: { de: 'Euphemismus', sentence_de: 'Das ist ein Euphemismus.' },
  518: { de: 'Paradoxon', sentence_de: 'Das ist ein interessantes Paradoxon.' },
  519: { de: 'Dilemma', sentence_de: 'Ich habe ein Dilemma.' },
  520: { de: 'Heuchelei', sentence_de: 'Ich ertrage keine Heuchelei.' },
  521: { de: 'Lage / Konjunktur', sentence_de: 'Die wirtschaftliche Lage ist schwierig.' },
  522: { de: 'Verwurzelung', sentence_de: 'Er ist in der Gemeinschaft verwurzelt.' },
  523: { de: 'nachforschen / ermitteln', sentence_de: 'Man muss weiter ermitteln.' },
  524: { de: 'ausweichen / umgehen', sentence_de: 'Du kannst der Verantwortung nicht ausweichen.' },
  525: { de: 'einflößen / vermitteln', sentence_de: 'Ich will Vertrauen einflößen.' },
  526: { de: 'verwirren / irritieren', sentence_de: 'Die Antwort hat mich verwirrt.' },
  527: { de: 'nach sich ziehen / verursachen', sentence_de: 'Es kann Probleme nach sich ziehen.' },
  528: { de: 'aufschlüsseln / aufgliedern', sentence_de: 'Man muss die Kosten aufschlüsseln.' },
  529: { de: 'zugrunde liegen', sentence_de: 'Es gibt ein zugrunde liegendes Problem.' },
  530: { de: 'widerlegen', sentence_de: 'Ich kann das nicht widerlegen.' },
  531: { de: 'fehlen / mangeln an', sentence_de: 'Es ergibt keinen Sinn.' },
  532: { de: 'umgehen / ausweichen', sentence_de: 'Das Thema lässt sich nicht umgehen.' },
  533: { de: 'horten / anhäufen', sentence_de: 'Man soll nicht alles horten.' },
  534: { de: 'genau prüfen / durchleuchten', sentence_de: 'Man muss die Daten genau prüfen.' },
  535: { de: 'beilegen / klären', sentence_de: 'Man muss die Diskussion beilegen.' },
  536: { de: 'Detail / Einzelheit', sentence_de: 'Er erklärte jede Einzelheit.' },
  537: { de: 'aufkeimend / beginnend', sentence_de: 'Es ist ein aufkeimender Trend.' },
  538: { de: 'knapp / kurz', sentence_de: 'Es war eine knappe Antwort.' },
  539: { de: 'glühend / leidenschaftlich', sentence_de: 'Er ist ein glühender Verfechter.' },
  540: { de: 'unmittelbar bevorstehend', sentence_de: 'Die Veränderung steht unmittelbar bevor.' },
  541: { de: 'geeignet / ideal', sentence_de: 'Er ist der geeignete Kandidat.' },
  542: { de: 'eisern / unerschütterlich', sentence_de: 'Er hat einen eisernen Willen.' },
  543: { de: 'kategorisch / bestimmt', sentence_de: 'Es war eine kategorische Antwort.' },
  544: { de: 'verschwindend gering', sentence_de: 'Die Kosten sind verschwindend gering.' },
  545: { de: 'vergänglich / flüchtig', sentence_de: 'Ruhm ist vergänglich.' },
  546: { de: 'düster / finster', sentence_de: 'Die Aussicht ist düster.' },
  547: { de: 'verhängnisvoll / unheilvoll', sentence_de: 'Es war ein verhängnisvoller Tag.' },
  548: { de: 'schrittweise / allmählich', sentence_de: 'Es gab eine schrittweise Veränderung.' },
  549: { de: 'verborgen / abgelegen', sentence_de: 'Ein verborgener Ort.' },
  550: { de: 'gewaltig / immens', sentence_de: 'Es erfordert eine gewaltige Anstrengung.' },
  // C2
  601: { de: 'Schlupfloch / Spalt', sentence_de: 'Er fand ein rechtliches Schlupfloch.' },
  602: { de: 'Schmährede / Tirade', sentence_de: 'Er startete eine Tirade gegen alle.' },
  603: { de: 'Winkel / Feinheiten', sentence_de: 'Er kennt die Feinheiten des Themas.' },
  604: { de: 'Abhandlung / Erörterung', sentence_de: 'Er hielt eine lange Erörterung.' },
  605: { de: 'entschädigen', sentence_de: 'Der Schaden muss entschädigt werden.' },
  606: { de: 'aufklären / erläutern', sentence_de: 'Die Fakten müssen aufgeklärt werden.' },
  607: { de: 'sparen / knausern', sentence_de: 'Er sparte nicht an Ausgaben.' },
  608: { de: 'abwägen', sentence_de: 'Man muss die Optionen abwägen.' },
  609: { de: 'sich aneignen / usurpieren', sentence_de: 'Er versuchte die Macht an sich zu reißen.' },
  610: { de: 'verschärfen / verschlimmern', sentence_de: 'Die Lage hat sich verschärft.' },
  611: { de: 'schmähen / verunglimpfen', sentence_de: 'Man soll niemanden schmähen.' },
  612: { de: 'bestätigen / bekräftigen', sentence_de: 'Die Daten bestätigen die Theorie.' },
  613: { de: 'erahnen / vorausahnen', sentence_de: 'Man kann die Zukunft erahnen.' },
  614: { de: 'einschüchtern', sentence_de: 'Du wirst mich nicht einschüchtern.' },
  615: { de: 'verletzen / kränken', sentence_de: 'Ich will dich nicht verletzen.' },
  616: { de: 'auffordern / ermahnen', sentence_de: 'Sie forderten ihn zum Rücktritt auf.' },
  617: { de: 'Umschreibung', sentence_de: 'Sprich ohne Umschweife.' },
  618: { de: 'gewunden / kurvenreich', sentence_de: 'Der Weg ist kurvenreich.' },
  619: { de: 'auffallend / hervorragend', sentence_de: 'Er ist eine auffallende Persönlichkeit.' },
  620: { de: 'widerspenstig / störrisch', sentence_de: 'Er ist ein widerspenstiger Gegner.' },
  621: { de: 'verwickelt / kompliziert', sentence_de: 'Der Prozess ist verwickelt.' },
  622: { de: 'glaubwürdig / beweiskräftig', sentence_de: 'Es ist ein glaubwürdiger Beweis.' },
  623: { de: 'vertrauenswürdig / zuverlässig', sentence_de: 'Es ist eine zuverlässige Quelle.' },
  624: { de: 'ewig / immerwährend', sentence_de: 'Es ist ein ewiges Problem.' },
  625: { de: 'unbeschreiblich / unsagbar', sentence_de: 'Ich fühlte eine unbeschreibliche Freude.' },
  626: { de: 'führerlos / kopflos', sentence_de: 'Die Organisation ist führerlos.' },
  627: { de: 'hartnäckig / halsstarrig', sentence_de: 'Er ist ein hartnäckiger Mann.' },
  628: { de: 'schmachvoll / schändlich', sentence_de: 'Es war eine schmachvolle Niederlage.' },
  629: { de: 'Großzügigkeit / Freigebigkeit', sentence_de: 'Seine Großzügigkeit ist bekannt.' },
  630: { de: 'Verwurzelung / Tradition', sentence_de: 'Es ist ein tief verwurzelter Brauch.' },
  631: { de: 'Bestürzung / Betäubung', sentence_de: 'Die Nachricht löste Bestürzung aus.' },
  632: { de: 'Spur / Überrest', sentence_de: 'Es blieb keine Spur übrig.' },
  633: { de: 'Einwilligung / Zustimmung', sentence_de: 'Ich brauche deine Zustimmung.' },
  634: { de: 'beharrlich / hartnäckig', sentence_de: 'Es war eine beharrliche Dürre.' },
  635: { de: 'hervorragend / erlaucht', sentence_de: 'Er war ein hervorragender Denker.' },
  636: { de: 'wortkarg / lakonisch', sentence_de: 'Er gab eine wortkarge Antwort.' },
  637: { de: 'Lobrede / Lobpreisung', sentence_de: 'Er hielt eine Lobrede.' },
  638: { de: 'Schmach / Schande', sentence_de: 'Es war eine öffentliche Schande.' },
  639: { de: 'verschwenden / großzügig geben', sentence_de: 'Er überschüttete alle mit Lob.' },
  640: { de: 'aufheben / abschaffen', sentence_de: 'Sie hoben das alte Gesetz auf.' },
  641: { de: 'aufhetzen / anstacheln', sentence_de: 'Man soll Menschen nicht aufhetzen.' },
  642: { de: 'hervorragen / sich auszeichnen', sentence_de: 'Er zeichnet sich unter seinen Kollegen aus.' },
  643: { de: 'überflüssig sein', sentence_de: 'Es versteht sich von selbst, dass es wichtig ist.' },
  644: { de: 'verletzen (Gesetz) / missachten', sentence_de: 'Sie missachteten die Rechte.' },
  645: { de: 'entfremden', sentence_de: 'Er entfremdete sich von der Realität.' },
  646: { de: 'durcheinanderbringen / umstürzen', sentence_de: 'Er brachte alle Pläne durcheinander.' },
  647: { de: 'Anrede / Apostrophe (Rhetorik)', sentence_de: 'Er verwendete eine dramatische Anrede.' },
  648: { de: 'Inbegriff / Verkörperung', sentence_de: 'Er ist der Inbegriff der Eleganz.' },
  649: { de: 'kindisch / unreif', sentence_de: 'Das ist ein kindisches Argument.' },
  650: { de: 'glaubhaft / plausibel', sentence_de: 'Die Geschichte ist plausibel.' },
};

const filePath = path.join(__dirname, '..', 'data', 'words.ts');
let content = fs.readFileSync(filePath, 'utf-8');

for (const [id, data] of Object.entries(germanData)) {
  const escapedDe = data.de.replace(/'/g, "\\'");
  const escapedSentence = data.sentence_de.replace(/'/g, "\\'");

  // Find the line with this id and add de + sentence_de before sentence_en
  const regex = new RegExp(
    `(\\{ id: ${id},.*?sentence_en: '[^']*')( \\})`,
  );

  if (!content.match(regex)) {
    // Try with escaped quotes
    const regex2 = new RegExp(
      `(\\{ id: ${id},.*?sentence_en: '.*?(?<!\\\\)')( \\})`,
    );
    content = content.replace(regex2, `$1, de: '${escapedDe}', sentence_de: '${escapedSentence}'$2`);
  } else {
    content = content.replace(regex, `$1, de: '${escapedDe}', sentence_de: '${escapedSentence}'$2`);
  }
}

fs.writeFileSync(filePath, content);
console.log('German translations added to all words.');
console.log('Verifying...');
const deCount = (content.match(/sentence_de:/g) || []).length;
console.log(`Found ${deCount} sentence_de entries.`);
